version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Vinay@7782
      MYSQL_DATABASE: monolithic
      MYSQL_USER: vinay
      MYSQL_PASSWORD: Vinay@7782
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: java-app
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: monolithic
      DB_USER: vinay
      DB_PASSWORD: Vinay@7782
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  mysql_data:
